buildo/avenger

fixtures/queries.js, package.json, src/util.js, test/tests/index.js
=> #17 replace ramda with lodash

src/Query.js
=> #16 t.Func is irreducible

fixtures/queries.js, src/index.js, test/tests/index.js
=> #23 support multiple dependencies per query in avenger.schedule

src/index.js
=> #40: QS emitter off (closes #40)

fixtures/queries.js, src/Query.js, src/internals.js, test/tests/internals.js
=> #43: Query.cacheParams (closes #43)

package.json, src/internals.js, test/tests/Avenger.js
=> #46: Skip minCache for non cached queries (closes #46)

src/index.js
=> #48: Basic logging in Avenger index (closes #48)

src/AvengerCache.js, src/internals.js
=> #50: moar logs (closes #50)

src/AvengerCache.js
=> #52: Fix AvengerCache set() (closes #52)

src/index.js
=> #55: add QS.cached() for emitting cached updates only (closes #55)

package.json, src/index.js, src/internals.js, test/tests/Avenger.js
=> #57: patchCache + data instead of initialCache in constructor (closes #57)

src/index.js, test/tests/Avenger.js
=> #61: temp _meta for readyState (closes #61)

src/index.js, test/tests/Avenger.js
=> return result with _meta from run, fix tests accordingly

src/AvengerCache.js, src/Command.js, src/Query.js, src/index.js, src/internals.js, test/tests/Avenger.js
=> implement runCommand for client-side-only avenger

src/run.js
=> #67: fix undefined reject in createFetcher (closes #67)

npm-shrinkwrap.json.reference, package.json
=> #70: update deps (closes #70)

src/types.js, test/tests/AvengerCache.js
=> #73: support dates as cache params (closes #73)

src/downset.js, src/run.js, test/tests/Avenger.js, test/tests/run.js
=> #75: be sure to run() entire downset for diffed queries (closes #75)

src/AvengerCache.js, src/createFetcher.js
=> #77: Fix: falsy values from cache are not considered (closes #77)

.babelrc, package.json, src/Avenger.js, src/AvengerCache.js, src/build.js, src/createFetcher.js, src/downset.js, src/invalidate.js, src/positiveDiff.js, src/run.js, src/types.js, src/upset.js, src/util.js, test/index.js, test/tests/Avenger.js
=> [WIP] #81: use babel-plugin-tcomb (closes #81)

src/Avenger.js
=> #84: fix buggish handling of null and falsy values (closes #84)

src/Avenger.js
=> #86: $av global when running development (closes #86)

package.json, src/Avenger.js
=> #88: be sure to always emit boolean flags in __meta (closes #88)

.travis.yml, README.md
=> #101: Use Travis CI (closes #101)

src/invalidate.js, src/minDepsParams.js, src/types.js
=> #99: `map` should be optional (closes #99)

src/Avenger.js
=> #92: emitter.off doesn't exist (closes #92)

src/types.js
=> #45: Support null and/or undefined params in state params (closes #45)

src/Avenger.js, test/tests/Avenger.js
=> #95: Don't expose EventEmitter in the public API (closes #95)

package.json, src/build.js, src/createFetcher.js, src/util.js
=> update lodash to 4 (closes #108)

src/query/query.js
Issue #121
re-run the "how to reproduce" steps a few times without encountering the issue
=> #121: prevent possible ".hasOwnProperty of null" (closes #121)

package.json
=> #123: update to latest rxjs version (closes #123)

src/graph/index.js, src/graph/query.js, src/query/apply.js, src/query/query.js, test/graph/querySync.test.js
Issue #119
see `querySync.test.js`
=> #119: provide sync API for queries (closes #119)

src/graph/Command.js, src/graph/QueryNode.js, src/graph/index.js, src/graph/runCommand.js, test/graph/deps.test.js, test/graph/invalidate.test.js, test/graph/querySync.test.js
Issue #125
tested manually on qia
will not add tests just yet since this api is still very tentative
=> #125: add `Query` and `Command` helpers (closes #125)

src/query/observe.js, src/query/query.js
Hey there,
this PR was opened using [linto](https://github.com/buildo/linto).
Usually this means the shared ESLint config has been updated and these are the changes needed to comply with the new config.
The diff for this PR has been generated running `eslint --fix` using the updated ESLint config. Depending on the specific change, you may need to apply some manual fixes too.
Hope this helped!
Your friend,
linto 💄
=> 💄  linto fix

src/graph/Command.js, src/graph/QueryNode.js
Issue #129
tested manually on gdsm and qia
=> #129: add `QueryNode.upsetParams` and `Command.invalidateParams` (closes #129)

src/graph/QueryNode.js
Closes #133
> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}
=> #133: add a (temporary) shortcut to avoid serializing big payloads as part of a cache key (closes #133)

package.json, typings/graph.d.ts, typings/strategies.d.ts
Closes #148
> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}
=> #148: Add typescript definition files (closes #148)

src/runCommand.js
=> #159: runCommand overwrites dependencies results with queries passed as params causing bugs (closes #159)

package.json, src/index.d.ts
=> #164: support for TS 2.9+ in major minor version (closes #164)

package.json, src/cache/Cache.js, src/query/ObservableCache.js, src/query/query.js, test/query/query.test.js
see added (and previously failing) tests
=> Emit error behavior (closes #170)

src/index.d.ts
Closes #168
Tried this in `react-avenger` in this PR:
https://github.com/buildo/react-avenger/pull/67
=> #168: BROKEN_FlattenObject does not actually flatten objects (closes #168)

src/cache/Cache.js, src/cache/operators.js, src/cache/strategies.js
=> #172: cachestrategy validation is broken with new io-ts (closes #172)

package.json
=> #174: io-ts should be listed in the project dependencies (closes #174)

.travis.yml, ci/pipeline.yml, ci/test.sh, ci/test.yml
It works:
https://concourse.our.buildo.io/teams/buildo/pipelines/avenger/jobs/pr-test/builds/3
=> No more travis

dtslint/ts3.5/index.tsx, src/browser/location.ts
Closes #202
tested manually on an internal project
Unfortunately this code path is not actually tested fullstack (the underlying query/commands and interactions with history are, but not the React part itself), but adding a test actually rendering react would require some effort
> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with …
=> #202: browser/location.ts: pendingUpdateLocation is not invalidated (closes #202)

package.json, src/Query.ts, test/Query.test.ts
Closes #205
See added unit tests
=> #205: Add Query mapLeft (closes #205)

src/Query.ts, test/Query.test.ts, test/Strategy.test.ts
=> #210: map()ed query not correctly linked with the original one (closes #210)

dtslint/ts3.7/index.tsx, src/react/WithQueries.tsx, test/RWC.test.ts, test/memoryValue.test.ts, test/observe.test.ts
Closes #214
Tested manually on a project.
Unfortunately hard to add a React automated test now since we don't have the infra in place
=> #214: WithQueries: honour the last "render" prop received (closes #214)

src/react/useQueries.ts, test/WithQueries.test.tsx, test/declareQueries.test.tsx, test/useQueries.test.tsx
Closes #219
See the added unit tests
=> #219: useQueries re-render components not included  into chain
